sudo: false
language: python
python: 3.6
env:
  matrix:
  - TESTENV=py27-pytest2
  - TESTENV=py34-pytest2
  - TESTENV=py35-pytest2
  - TESTENV=py27-pytest3
  - TESTENV=py34-pytest3
  - TESTENV=py35-pytest3
  - TESTENV=py36-pytest3
install:
- pip install tox
script: tox -e $TESTENV
branches:
    except:
        - /^\d/
notifications:
    email:
        - bubenkoff@gmail.com
        - oleg.pidsadnyi@gmail.com
